
order_flow <- c("Exclude males",
                "Exclude age <18",
                "Exclude not SUI",
                "Exclude no visit prior year",
                "Exclude prior SUI",
                "Exclude non-sling",
                "Exclude prior diverticulum",
                "Exclude surgeries before 1-1-2010",
                "Exclude multiple/subsequent surgeries",
                "Exclude NLP no mesh or indeterminate mesh from any prolapse",
                "Exclude prior prolapse",
                "Exclude NLP no mesh or indeterminate mesh from no prior prolapse")

order_dem_fac <- c("FEMALE", 
                   "RACE_AMERICAN_INDIAN_ALASKA_NATIVE",
                   "RACE_ASIAN",
                   "RACE_BLACK",
                   "RACE_NATIVE_HAWAIIAN_PACIFIC_ISLANDER",
                   "RACE_WHITE",
                   "RACE_UNKNOWN",
                   "HISPANIC")

order_dem_num <- c("AGE_PROCEDURE")

order_med_fac <- c("HISTORYMENOPAUSE",      
                   "HISTORYSMOKING",
                   "PRESURGERYCAD",
                   "PRESURGERYDM",
                   "PRESURGERYHLD",
                   "PRESURGERYHTN",         
                   "PRESURGERYPVD",
                   "PRIORDIVERICULUM",
                   "PRIORPROLAPSE",
                   "PRIORSUI",
                   "PREABSURG",
                   "PERIABSURG",
                   "PREHISTORYCHRONICPAIN", 
                   "PERIHISTORYCHRONICPAIN",
                   "VISITYEARPRIORSURGERY",
                   "VISITYEARPOSTSURGERY",
                   "URODYNAMICTESTING",
                   "SUI_IND", 
                   "LAP_SLING",
                   "CONCOMITANTSURG")

order_med_num <- c("BMI",
                   "DAYS_SURGERY_PREVOIDING",
                   "DAYS_SURGERY_PERIVOIDING")

order_drug_fac <- c("ATC_ACE_INHIBITORS_PLAIN",
                    "ATC_ACETIC_ACID_DERIVATIVES_AND_RELATED_SUBSTANCES",
                    "ATC_AMIDES",
                    "ATC_ANESTHETICS_FOR_TOPICAL_USE",
                    "ATC_ANESTHETICS_LOCAL",
                    "ATC_ANGIOTENSIN_II_ANTAGONISTS_PLAIN",
                    "ATC_ANILIDES",
                    "ATC_BENZODIAZEPINE_DERIVATIVES",
                    "ATC_BENZODIAZEPINE_RELATED_DRUGS",
                    "ATC_BETA_BLOCKING_AGENTS_SELECTIVE",
                    "ATC_BIGUANIDES",
                    "ATC_CORTICOSTEROIDS_PLAIN",
                    "ATC_DIHYDROPYRIDINE_DERIVATIVES",
                    "ATC_DRUGS_FOR_URINARY_FREQUENCY_AND_INCONTINENCE",
                    "ATC_ELECTROLYTE_SOLUTIONS",
                    "ATC_FIRST_GENERATION_CEPHALOSPORINS",
                    "ATC_FLUOROQUINOLONES",
                    "ATC_GLUCOCORTICOIDS",
                    "ATC_H2_RECEPTOR_ANTAGONISTS",
                    "ATC_HMG_COA_REDUCTASE_INHIBITORS",                  
                    "ATC_INTERMEDIATE_ACTING_SULFONAMIDES",
                    "ATC_NATURAL_AND_SEMISYNTHETIC_ESTROGENS_PLAIN",     
                    "ATC_NATURAL_OPIUM_ALKALOIDS",
                    "ATC_NITROFURAN_DERIVATIVES",                        
                    "ATC_NON_SELECTIVE_MONOAMINE_REUPTAKE_INHIBITORS",
                    "ATC_OPIOID_ANESTHETICS",                            
                    "ATC_OPIUM_ALKALOIDS_AND_DERIVATIVES",
                    "ATC_OTHER_ANTIDEPRESSANTS",                         
                    "ATC_OTHER_ANTIEPILEPTICS",
                    "ATC_OTHER_ANTIHISTAMINES_FOR_SYSTEMIC_USE",         
                    "ATC_OTHER_CENTRALLY_ACTING_AGENTS",
                    "ATC_OTHER_GENERAL_ANESTHETICS",                     
                    "ATC_OTHER_PLAIN_VITAMIN_PREPARATIONS",
                    "ATC_OTHER_QUATERNARY_AMMONIUM_COMPOUNDS",           
                    "ATC_OTHER_UROLOGICALS",
                    "ATC_PENICILLINS_WITH_EXTENDED_SPECTRUM",            
                    "ATC_PHENOTHIAZINE_DERIVATIVES",
                    "ATC_PHENYLPIPERIDINE_DERIVATIVES",                  
                    "ATC_PIPERAZINE_DERIVATIVES",
                    "ATC_PROPIONIC_ACID_DERIVATIVES",                    
                    "ATC_PROTON_PUMP_INHIBITORS",
                    "ATC_SELECTIVE_SEROTONIN_REUPTAKE_INHIBITORS",       
                    "ATC_SEROTONIN_5HT3_ANTAGONISTS",
                    "ATC_SOFTENERS_EMOLLIENTS",                          
                    "ATC_SULFONAMIDES_PLAIN",
                    "ATC_THIAZIDES_PLAIN",                               
                    "ATC_THYROID_HORMONES",
                    "ATC_TRIMETHOPRIM_AND_DERIVATIVES",                  
                    "ATC_VITAMIN_D_AND_ANALOGUES")

order_drug_num <- NA

order_lab_fac <- c("HGB_UA_MIN",
                   "HGB_UA_MEAN",
                   "HGB_UA_MEDIAN",
                   "HGB_UA_MAX",
                   "NITRITE_UA_MIN",
                   "NITRITE_UA_MEAN",
                   "NITRITE_UA_MEDIAN",
                   "NITRITE_UA_MAX")

order_lab_num <- c("ALBUMIN_BSP_MG_MIN",
                   "ALBUMIN_BSP_MG_MEAN",
                   "ALBUMIN_BSP_MG_MEDIAN",
                   "ALBUMIN_BSP_MG_MAX",
                   "ALT_BSP_MIN",
                   "ALT_BSP_MEAN",
                   "ALT_BSP_MEDIAN",
                   "ALT_BSP_MAX",
                   "AST_BSP_MIN",
                   "AST_BSP_MEAN",
                   "AST_BSP_MEDIAN",
                   "AST_BSP_MAX",
                   "BILI_TOTAL_BSP_MG_MIN",
                   "BILI_TOTAL_BSP_MG_MEAN",
                   "BILI_TOTAL_BSP_MG_MEDIAN",
                   "BILI_TOTAL_BSP_MG_MAX",
                   "CA_BSP_MG_MIN",
                   "CA_BSP_MG_MEAN",
                   "CA_BSP_MG_MEDIAN",
                   "CA_BSP_MG_MAX",
                   "CL_BSP_MMOL_MIN",
                   "CL_BSP_MMOL_MEAN",
                   "CL_BSP_MMOL_MEDIAN",
                   "CL_BSP_MMOL_MAX",
                   "CHOL_BSP_MG_MIN",
                   "CHOL_BSP_MG_MEAN",
                   "CHOL_BSP_MG_MEDIAN",
                   "CHOL_BSP_MG_MAX",
                   "CO2_BSP_MMOL_MIN",
                   "CO2_BSP_MMOL_MEAN",
                   "CO2_BSP_MMOL_MEDIAN",
                   "CO2_BSP_MMOL_MAX",
                   "CREAT_BSP_MG_MIN",
                   "CREAT_BSP_MG_MEAN",
                   "CREAT_BSP_MG_MEDIAN",
                   "CREAT_BSP_MG_MAX",
                   "FERRITIN_BSP_MG_MIN",
                   "FERRITIN_BSP_MG_MEAN",
                   "FERRITIN_BSP_MG_MEDIAN",
                   "FERRITIN_BSP_MG_MAX",
                   "GLUCOSE_BSP_MG_MIN",
                   "GLUCOSE_BSP_MG_MEAN",
                   "GLUCOSE_BSP_MG_MEDIAN",
                   "GLUCOSE_BSP_MG_MAX",
                   "HDL_BSP_MG_MIN",
                   "HDL_BSP_MG_MEAN",
                   "HDL_BSP_MG_MEDIAN",
                   "HDL_BSP_MG_MAX",
                   "HGB_BSP_GM_MIN",
                   "HGB_BSP_GM_MEAN",
                   "HGB_BSP_GM_MEDIAN",
                   "HGB_BSP_GM_MAX",
                   "HGBA1C_BSP_MIN",
                   "HGBA1C_BSP_MEAN",
                   "HGBA1C_BSP_MEDIAN",
                   "HGBA1C_BSP_MAX",
                   "INR_BSP_MIN",
                   "INR_BSP_MEAN",
                   "INR_BSP_MEDIAN",
                   "INR_BSP_MAX",
                   "I_CALCIUM_BSP_MG_MIN",
                   "I_CALCIUM_BSP_MG_MEAN",
                   "I_CALCIUM_BSP_MG_MEDIAN",
                   "I_CALCIUM_BSP_MG_MAX",
                   "IRON_BSP_MG_MIN",
                   "IRON_BSP_MG_MEAN",
                   "IRON_BSP_MG_MEDIAN",
                   "IRON_BSP_MG_MAX",
                   "KETONES_UA_MIN",
                   "KETONES_UA_MEAN",
                   "KETONES_UA_MEDIAN",
                   "KETONES_UA_MAX",
                   "LDL_BSP_MG_MIN",
                   "LDL_BSP_MG_MEAN",
                   "LDL_BSP_MG_MEDIAN",
                   "LDL_BSP_MG_MAX",
                   "WBC_BSP_CNT_MIN",
                   "WBC_BSP_CNT_MEAN",
                   "WBC_BSP_CNT_MEDIAN",
                   "WBC_BSP_CNT_MAX",
                   "MAGNESIUM_BSP_MG_MIN",
                   "MAGNESIUM_BSP_MG_MEAN",
                   "MAGNESIUM_BSP_MG_MEDIAN",
                   "MAGNESIUM_BSP_MG_MAX",
                   "MCHC_BSP_GM_MIN",
                   "MCHC_BSP_GM_MEAN",
                   "MCHC_BSP_GM_MEDIAN",
                   "MCHC_BSP_GM_MAX",
                   "MCV_BSP_FL_MIN",
                   "MCV_BSP_FL_MEAN",
                   "MCV_BSP_FL_MEDIAN",
                   "MCV_BSP_FL_MAX",
                   "PHOSPHATE_BSP_MG_MIN",
                   "PHOSPHATE_BSP_MG_MEAN",
                   "PHOSPHATE_BSP_MG_MEDIAN",
                   "PHOSPHATE_BSP_MG_MAX",
                   "PLT_BSP_CNT_MIN",
                   "PLT_BSP_CNT_MEAN",
                   "PLT_BSP_CNT_MEDIAN",
                   "PLT_BSP_CNT_MAX",
                   "K_BSP_MMOL_MIN",
                   "K_BSP_MMOL_MEAN",
                   "K_BSP_MMOL_MEDIAN",
                   "K_BSP_MMOL_MAX",
                   "PROTEIN_UA_MIN",
                   "PROTEIN_UA_MEAN",
                   "PROTEIN_UA_MEDIAN",
                   "PROTEIN_UA_MAX",
                   "PTT_BSP_MIN",
                   "PTT_BSP_MEAN",
                   "PTT_BSP_MEDIAN",
                   "PTT_BSP_MAX",
                   "RBC_UA_CNT_MIN",
                   "RBC_UA_CNT_MEAN",
                   "RBC_UA_CNT_MEDIAN",
                   "RBC_UA_CNT_MAX",
                   "NA_BSP_MMOL_MIN",
                   "NA_BSP_MMOL_MEAN",
                   "NA_BSP_MMOL_MEDIAN",
                   "NA_BSP_MMOL_MAX",
                   "TSH_BSP_MIU_MIN",
                   "TSH_BSP_MIU_MEAN",
                   "TSH_BSP_MIU_MEDIAN",
                   "TSH_BSP_MIU_MAX",
                   "T4_BSP_UG_MIN",
                   "T4_BSP_UG_MEAN",
                   "T4_BSP_UG_MEDIAN",
                   "T4_BSP_UG_MAX",
                   "TIBC_BSP_MG_MIN",
                   "TIBC_BSP_MG_MEAN",
                   "TIBC_BSP_MG_MEDIAN",
                   "TIBC_BSP_MG_MAX",
                   "TRANSFERRIN_BSP_MG_MIN",
                   "TRANSFERRIN_BSP_MG_MEAN",
                   "TRANSFERRIN_BSP_MG_MEDIAN",
                   "TRANSFERRIN_BSP_MG_MAX",
                   "TRIG_BSP_MG_MIN",
                   "TRIG_BSP_MG_MEAN",
                   "TRIG_BSP_MG_MEDIAN",
                   "TRIG_BSP_MG_MAX",
                   "TROP_I_BSP_MG_MIN",
                   "TROP_I_BSP_MG_MEAN",
                   "TROP_I_BSP_MG_MEDIAN",
                   "TROP_I_BSP_MG_MAX",
                   "TROP_T_BSP_MG_MIN",
                   "TROP_T_BSP_MG_MEAN",
                   "TROP_T_BSP_MG_MEDIAN",
                   "TROP_T_BSP_MG_MAX",
                   "BUN_BSP_MG_MIN",
                   "BUN_BSP_MG_MEAN",
                   "BUN_BSP_MG_MEDIAN",
                   "BUN_BSP_MG_MAX",
                   "SP_GRAVITY_UA_MIN",
                   "SP_GRAVITY_UA_MEAN",
                   "SP_GRAVITY_UA_MEDIAN",
                   "SP_GRAVITY_UA_MAX")

order_out_fac <- c("POSTABSURG",
                   "POSTHISTORYCHRONICPAIN",
                   "FOLLOWUP30d",
                   "FOLLOWUP90d",
                   "FOLLOWUP1Y",
                   "FOLLOWUP2Y",
                   "FOLLOWUP5Y",
                   "FOLLOWUPevent",
                   "DEATH30d",
                   "DEATH90d",
                   "DEATH1Y",
                   "DEATH2Y",
                   "DEATH5Y",
                   "DEATHevent",
                   "FISTULA30d",
                   "FISTULA90d",
                   "FISTULA1Y",
                   "FISTULA2Y",
                   "FISTULA5Y",
                   "FISTULAevent",
                   "INFECTION7d",
                   "INFECTION14d",
                   "INFECTION30d",
                   "INFECTIONevent",
                   "EROSION30d",
                   "EROSION90d",
                   "EROSION1Y",
                   "EROSION2Y",
                   "EROSION5Y",
                   "EROSIONevent",
                   "REMOVAL30d",
                   "REMOVAL90d",
                   "REMOVAL1Y",
                   "REMOVAL2Y",
                   "REMOVAL5Y",
                   "REMOVALevent",
                   "PAIN30d",
                   "PAIN90d",
                   "PAIN1Y",
                   "PAIN2Y",
                   "PAIN5Y",
                   "PAINevent",
                   "PERFORATION30d",
                   "PERFORATION90d",
                   "PERFORATION1Y",
                   "PERFORATION2Y",
                   "PERFORATION5Y",
                   "PERFORATIONevent",
                   "REOPERATION30d",
                   "REOPERATION90d",
                   "REOPERATION1Y",
                   "REOPERATION2Y",
                   "REOPERATION5Y",
                   "REOPERATIONevent",
                   "INDICATION_REOPERATION",
                   "POSTVOIDING30d",
                   "POSTVOIDING90d",
                   "POSTVOIDING1Y",
                   "POSTVOIDING2Y",
                   "POSTVOIDING5Y",
                   "POSTVOIDINGevent")

order_out_num <- c("DAYS_FOLLOWUP",
                   "DAYS_SURGERY_MOST_RECENT_INPAT_VISIT",
                   "DAYS_SURGERY_MOST_RECENT_OUTPAT_VISIT",
                   "DAYS_SURGERY_DEATH",
                   "DAYS_SURGERY_FISTULA",                 
                   "DAYS_SURGERY_INFECTION",
                   "DAYS_SURGERY_EROSION",
                   "DAYS_SURGERY_REMOVAL",
                   "DAYS_SURGERY_PAIN",
                   "DAYS_SURGERY_PERFORATION",
                   "DAYS_SURGERY_REOPERATION",             
                   "DAYS_SURGERY_POSTVOIDING")

order_nlp_fac <- c("REGEX_ADJ_SLING",
                   "REGEX_RETROPUBIC",
                   "REGEX_SNGL_INC",
                   "REGEX_TRANSOB",
                   "REGEX_UNKNOWN",
                   "REGEX_MESH",
                   "REGEX_NO_MESH",
                   "REGEX_INDETERMINATE_MESH")

order_nlp_num <- NA

order_chart_short <- c("INT_IMPLANT_BULKING_AGENTS",
                       "INT_IMPLANT_BURCH",
                       "INT_IMPLANT_CAD_ALLOGRAFT",
                       "INT_IMPLANT_PORCINE",
                       "INT_IMPLANT_PUBO_VAGINAL_AUTO",
                       "CHART_ADJ_SNGL_INC",
                       "CHART_RETROPUBIC",
                       "CHART_TRANSOB",
                       "CHART_APP_OTHER",
                       "CHART_MESH",
                       "CHART_NO_MESH",     
                       "CHART_INDETERMINATE_MESH")

order_chart_med_fac <- c("hx_of_bariatric_surgery",
                         "prior_hysterectomy",
                         "prior_oophorectomy",
                         "prior_prolapse",
                         "prior_sui",
                         "HISTORYMENOPAUSE_PRE",
                         "HISTORYMENOPAUSE_POST",
                         "HISTORYMENOPAUSE_UNKNOWN",
                         "SMOKING_STATUS_CURRENT",
                         "SMOKING_STATUS_FORMER",
                         "SMOKING_STATUS_NEVER",
                         "dyspareunia", #symptoms pre
                         "mixed",
                         "occult",
                         "dribble",
                         "severe",
                         "stress",
                         "urge",
                         "urgency",
                         "obstruction",
                         "retention",
                         "cystocele", #exam
                         "pelvic",
                         "rectocele",
                         "urethrocele",
                         "uterine_prolapse",         
                         "uterovaginal",
                         "enterocele",
                         "hysterectomy",
                         "vault_prolapse_enterocele",
                         "COUGH_STRESS_POSITIVE",
                         "COUGH_STRESS_NEGATIVE",  
                         "COUGH_STRESS_NOT_DONE",
                         "CONCOMITANTSURG_CHART")

order_chart_med_num <- c("bmi",
                         "years_prior_hysterectomy",
                         "years_prior_oophorectomy",
                         "years_prior_prolapse",
                         "years_prior_sui")

order_chart_pro_fac <- c("bladder_urethral_injury", #post-op complication
                         "bowel_injury",
                         "hemorrhage_or_bleeding_fro",
                         "mesh_erosion_exposure",
                         "need_for_blood_transfusion",
                         "pain_or_nerve_injury_after",
                         "prior_surgical_site_infect",
                         "retropubic_hematoma",
                         "surgical_site_infection",
                         "organ_perforation_from_mes", 
                         "urethral_fistula",
                         "urethral_injury",
                         "vascular_injury",
                         "INT_IMPLANT_BULKING_AGENTS",
                         "INT_IMPLANT_BURCH",
                         "INT_IMPLANT_CAD_ALLOGRAFT",
                         "INT_IMPLANT_PORCINE",
                         "INT_IMPLANT_PUBO_VAGINAL_AUTO",
                         "CHART_ADJ_SNGL_INC",
                         "CHART_RETROPUBIC",
                         "CHART_TRANSOB",
                         "CHART_APP_OTHER",
                         "CHART_MESH",
                         "CHART_NO_MESH",
                         "CHART_INDETERMINATE_MESH")

order_chart_pro_num <- NA

order_chart_out_fac <- c("abdominal_prolapse_repair", #reoperation
                         "anterior_colporrhaphy_repa",
                         "anterior_vesicourethropexy",
                         "autologous_tissue_sling",
                         "bladder_neck_suspension_gi",
                         "bulking_agents",
                         "burch_colposuspension_tran",
                         "cadaveric_fascial_sling",
                         "collagen_implant_into_the",
                         "cystocele_rectocele_repair",
                         "enterocele_vault_repair",
                         "fascia_removal",
                         "kelly_plication_of_urethro",   
                         "paravaginal_defect_repair",
                         "robotic_prolapse_repair",
                         "sacrospinous_ligament_fixa",
                         "salcrocolpopexy",               
                         "sling_combined_with_prolap",
                         "synthetic_mesh_removal",
                         "trans_vaginal_adjustable_s",
                         "trans_vaginal_retro_pubic",
                         "trans_vaginal_single_incis",
                         "trans_vaginal_trans_obtura",
                         "urethral_suspension",
                         "urethropexy_marshall_march",
                         "vaginal_prolapse_repair",
                         "laparoscopic",
                         "open",
                         "complete_removal_of_sling", #removal or revision
                         "removal_of_2cm_includes_cu",
                         "loosening_of_sling",
                         "chronic_pelvic_or_groin_pa", #post-procedure
                         "deceased",                 
                         "dyspareunia_discharge_or_b",
                         "fistula",
                         "groin_pain",
                         "incomplete_bladder_emptyin",
                         "misplaced_or_migrated_bulk",
                         "partner_dyspareunia",
                         "urinary_incontinence_witho",
                         "urinary_incontinence_wo",
                         "vaginal_band",
                         "irritative_bladder_symptom", #erosion
                         "mesh_erosion_to_bladder_or",
                         "mesh_erosion_without_re_op",    
                         "mesh_exposure",              #exposure
                         "mesh_exposure_without_surg")

order_chart_out_num <- c("days_abdominal_prolapse_repair",
                         "days_anterior_colporrhaphy",
                         "days_anterior_vesicourethropexy",
                         "days_autologous_tissue_sling",          
                         "days_bladder_neck_suspension",
                         "days_bulking_agents",
                         "days_burch_colposuspension_tran",
                         "days_cadaveric_fascial_sling",
                         "days_collagen_implant",
                         "days_cystocele_rectocele_repair",
                         "DAYS_SURGERY_DEATH_CHART",
                         "days_fascia_removal",
                         "days_kelly_plication",
                         "days_mesh_erosion_without_reop",
                         "days_paravaginal_defect_repair",
                         "days_robotic_prolapse_repair",
                         "days_sling_combined_prolapse_repair",
                         "days_synthetic_mesh_removal",
                         "days_urethral_suspension",
                         "days_urethropexy",                      
                         "days_urinary_incontinence_without_reop",
                         "days_vaginal_prolapse_repair")

order_comp_med_fac <- c("PREABSURG_DISCORDANT",
                        "PREHISTORYCHRONICPAIN_DISCORDANT",
                        "HISTORYMENOPAUSE_DISCORDANT",     
                        "PRIORPROLAPSE_DISCORDANT",
                        "HISTORYSMOKING_DISCORDANT",
                        "PRIORSUI_DISCORDANT",
                        "PREVOIDING_DISCORDANT",
                        "URODYNAMICTESTING_DISCORDANT",
                        "SUI_IND_DISCORDANT",
                        "CONCOMITANTSURG_DISCORDANT")

order_comp_med_num <- c("BMI_COMPARE")

order_comp_pro_fac <- c("MESH_DISCORDANT_SCR",
                        "NO_MESH_DISCORDANT_SCR",
                        "INDETERMINATE_MESH_DISCORDANT_SCR")

order_comp_pro_num <- NA

order_comp_out_fac <- c("DEATH_DISCORDANT",
                        "FISTULA_DISCORDANT",
                        "POSTHISTORYCHRONICPAIN_DISCORDANT",
                        "INFECTION_DISCORDANT",             
                        "EROSION_DISCORDANT",
                        "REMOVAL_DISCORDANT",
                        "PAIN_DISCORDANT",
                        "PERFORATION_DISCORDANT",           
                        "REOPERATION_DISCORDANT",
                        "POSTVOIDING_DISCORDANT")

order_comp_out_num <- c("DAYS_SURGERY_DEATH_COMPARE")

order_comp_pro_rs <- c("MESH_DISCORDANT_RS",
                       "NO_MESH_DISCORDANT_RS",
                       "INDETERMINATE_MESH_DISCORDANT_RS")

order_comp_pro_rscr <- c("MESH_DISCORDANT_RCR",
                         "NO_MESH_DISCORDANT_RCR",
                         "INDETERMINATE_MESH_DISCORDANT_RCR")

order_comp_app_rscr <- c("ADJ_SNGL_INC_DISCORDANT",          
                         "RETROPUBIC_DISCORDANT",            
                         "TRANSOB_DISCORDANT",               
                         "APP_UNKNOWN_DISCORDANT")
